### ISSUE TITLE
DGNLOFI radio station does not work

### ISSUE THREAD

**Issue by tarnjotsingh** [tarnjotsingh/gurmat-bot-issue-tracker#1]
The station for DGNLOFI has a broken youtube link that needs to be updated.

**Comment by tanishqahluwalia25** [comment]
Where is the working code?

**Comment by tarnjotsingh** [comment]
> Where is the working code?

It's currently in a private repository. I haven't opened this up to anybody yet even if isn't anything elaborate.

**Comment by tarnjotsingh** [comment]
This has been resolved by containerising the application
